version: '3.8'

services:
  rental:
    image: rental:1.0
    ports:
      - "5000:5000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    # volumes:
    #   - /opt/rental/data:/components/data:600
